# Generated by Django 2.2.5 on 2019-10-03 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0007_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userAdderss',
            new_name='userAddress',
        ),
    ]
