# Generated by Django 2.2.5 on 2019-10-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0011_auto_20191008_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='orderid',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
